// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/proto/messages.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_internal_proto_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_internal_proto_messages_proto_rawDescGZIP(), []int{0}
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_internal_proto_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_internal_proto_messages_proto_rawDescGZIP(), []int{1}
}

type Payment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cid           string                 `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	RequestedAt   string                 `protobuf:"bytes,3,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_internal_proto_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_internal_proto_messages_proto_rawDescGZIP(), []int{2}
}

func (x *Payment) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *Payment) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Payment) GetRequestedAt() string {
	if x != nil {
		return x.RequestedAt
	}
	return ""
}

type PurgePayments struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurgePayments) Reset() {
	*x = PurgePayments{}
	mi := &file_internal_proto_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurgePayments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurgePayments) ProtoMessage() {}

func (x *PurgePayments) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurgePayments.ProtoReflect.Descriptor instead.
func (*PurgePayments) Descriptor() ([]byte, []int) {
	return file_internal_proto_messages_proto_rawDescGZIP(), []int{3}
}

type PushPayment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payment       *Payment               `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	ProcessedBy   string                 `protobuf:"bytes,2,opt,name=processed_by,json=processedBy,proto3" json:"processed_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushPayment) Reset() {
	*x = PushPayment{}
	mi := &file_internal_proto_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushPayment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushPayment) ProtoMessage() {}

func (x *PushPayment) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushPayment.ProtoReflect.Descriptor instead.
func (*PushPayment) Descriptor() ([]byte, []int) {
	return file_internal_proto_messages_proto_rawDescGZIP(), []int{4}
}

func (x *PushPayment) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

func (x *PushPayment) GetProcessedBy() string {
	if x != nil {
		return x.ProcessedBy
	}
	return ""
}

type SummarizePayments struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummarizePayments) Reset() {
	*x = SummarizePayments{}
	mi := &file_internal_proto_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummarizePayments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummarizePayments) ProtoMessage() {}

func (x *SummarizePayments) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummarizePayments.ProtoReflect.Descriptor instead.
func (*SummarizePayments) Descriptor() ([]byte, []int) {
	return file_internal_proto_messages_proto_rawDescGZIP(), []int{5}
}

func (x *SummarizePayments) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *SummarizePayments) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type SummarizedProcessor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalRequests int64                  `protobuf:"varint,1,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`
	TotalAmount   string                 `protobuf:"bytes,2,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummarizedProcessor) Reset() {
	*x = SummarizedProcessor{}
	mi := &file_internal_proto_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummarizedProcessor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummarizedProcessor) ProtoMessage() {}

func (x *SummarizedProcessor) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummarizedProcessor.ProtoReflect.Descriptor instead.
func (*SummarizedProcessor) Descriptor() ([]byte, []int) {
	return file_internal_proto_messages_proto_rawDescGZIP(), []int{6}
}

func (x *SummarizedProcessor) GetTotalRequests() int64 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *SummarizedProcessor) GetTotalAmount() string {
	if x != nil {
		return x.TotalAmount
	}
	return ""
}

type SummarizedPayments struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Default       *SummarizedProcessor   `protobuf:"bytes,1,opt,name=default,proto3" json:"default,omitempty"`
	Fallback      *SummarizedProcessor   `protobuf:"bytes,2,opt,name=fallback,proto3" json:"fallback,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummarizedPayments) Reset() {
	*x = SummarizedPayments{}
	mi := &file_internal_proto_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummarizedPayments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummarizedPayments) ProtoMessage() {}

func (x *SummarizedPayments) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummarizedPayments.ProtoReflect.Descriptor instead.
func (*SummarizedPayments) Descriptor() ([]byte, []int) {
	return file_internal_proto_messages_proto_rawDescGZIP(), []int{7}
}

func (x *SummarizedPayments) GetDefault() *SummarizedProcessor {
	if x != nil {
		return x.Default
	}
	return nil
}

func (x *SummarizedPayments) GetFallback() *SummarizedProcessor {
	if x != nil {
		return x.Fallback
	}
	return nil
}

var File_internal_proto_messages_proto protoreflect.FileDescriptor

const file_internal_proto_messages_proto_rawDesc = "" +
	"\n" +
	"\x1dinternal/proto/messages.proto\x12\x03msg\"\x06\n" +
	"\x04Ping\"\x06\n" +
	"\x04Pong\"V\n" +
	"\aPayment\x12\x10\n" +
	"\x03cid\x18\x01 \x01(\tR\x03cid\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12!\n" +
	"\frequested_at\x18\x03 \x01(\tR\vrequestedAt\"\x0f\n" +
	"\rPurgePayments\"X\n" +
	"\vPushPayment\x12&\n" +
	"\apayment\x18\x01 \x01(\v2\f.msg.PaymentR\apayment\x12!\n" +
	"\fprocessed_by\x18\x02 \x01(\tR\vprocessedBy\"7\n" +
	"\x11SummarizePayments\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\"_\n" +
	"\x13SummarizedProcessor\x12%\n" +
	"\x0etotal_requests\x18\x01 \x01(\x03R\rtotalRequests\x12!\n" +
	"\ftotal_amount\x18\x02 \x01(\tR\vtotalAmount\"~\n" +
	"\x12SummarizedPayments\x122\n" +
	"\adefault\x18\x01 \x01(\v2\x18.msg.SummarizedProcessorR\adefault\x124\n" +
	"\bfallback\x18\x02 \x01(\v2\x18.msg.SummarizedProcessorR\bfallbackB;Z9github.com/rbenatti8/rinha-de-backend-2025/internal/protob\x06proto3"

var (
	file_internal_proto_messages_proto_rawDescOnce sync.Once
	file_internal_proto_messages_proto_rawDescData []byte
)

func file_internal_proto_messages_proto_rawDescGZIP() []byte {
	file_internal_proto_messages_proto_rawDescOnce.Do(func() {
		file_internal_proto_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_messages_proto_rawDesc), len(file_internal_proto_messages_proto_rawDesc)))
	})
	return file_internal_proto_messages_proto_rawDescData
}

var file_internal_proto_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_internal_proto_messages_proto_goTypes = []any{
	(*Ping)(nil),                // 0: msg.Ping
	(*Pong)(nil),                // 1: msg.Pong
	(*Payment)(nil),             // 2: msg.Payment
	(*PurgePayments)(nil),       // 3: msg.PurgePayments
	(*PushPayment)(nil),         // 4: msg.PushPayment
	(*SummarizePayments)(nil),   // 5: msg.SummarizePayments
	(*SummarizedProcessor)(nil), // 6: msg.SummarizedProcessor
	(*SummarizedPayments)(nil),  // 7: msg.SummarizedPayments
}
var file_internal_proto_messages_proto_depIdxs = []int32{
	2, // 0: msg.PushPayment.payment:type_name -> msg.Payment
	6, // 1: msg.SummarizedPayments.default:type_name -> msg.SummarizedProcessor
	6, // 2: msg.SummarizedPayments.fallback:type_name -> msg.SummarizedProcessor
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_proto_messages_proto_init() }
func file_internal_proto_messages_proto_init() {
	if File_internal_proto_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_messages_proto_rawDesc), len(file_internal_proto_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_proto_messages_proto_goTypes,
		DependencyIndexes: file_internal_proto_messages_proto_depIdxs,
		MessageInfos:      file_internal_proto_messages_proto_msgTypes,
	}.Build()
	File_internal_proto_messages_proto = out.File
	file_internal_proto_messages_proto_goTypes = nil
	file_internal_proto_messages_proto_depIdxs = nil
}
